name: Download openDAQ artifact from GitHub
description: "Download openDAQ artifact from GitHub workflow by run ID and artifact name"

inputs:
  opendaq-artifact-run-id:
    required: true

  opendaq-artifact-name:
    required: true

  destination-dir:
    required: false
    default: ${{ runner.temp }}

runs:
  using: composite
  steps:
  - name: Download openDAQ artifact
    shell: bash
    run: |
      DEST="${{ inputs.destination-dir }}"
      DEST=$(echo "$DEST" | sed 's|\\|/|g')

      ARTIFACT_NAME="${{ inputs.opendaq-artifact-name }}"
      ARTIFACT_DIR="$DEST/$ARTIFACT_NAME"

      gh run download "${{ inputs.opendaq-artifact-run-id }}" \
        --repo openDAQ/openDAQ \
        --pattern "$ARTIFACT_NAME" \
        --dir "$DEST"

      echo "$ARTIFACT_DIR/"
      ls -la "$ARTIFACT_DIR/"
