name: Install openDAQ framework package

inputs:
  opendaq-framework-package-filename:
    required: true

  opendaq-framework-package-path:
    required: false
    default: ${{ runner.temp }}

runs:
  using: composite

  steps:
    - name: Install openDAQ framework package (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $packagePath = Join-Path "${{ inputs.opendaq-framework-package-path }}" "${{ inputs.opendaq-framework-package-filename }}"
        $process = Start-Process -FilePath $packagePath -ArgumentList "/S" -Wait -NoNewWindow -PassThru
        if ($process.ExitCode -eq 0) {
            Write-Host "OpenDAQ installed successfully, updating PATH..."
            $openDAQBin = "C:\Program Files\openDAQ\bin"
            Add-Content -Path $env:GITHUB_ENV -Value "PATH=$openDAQBin`;$env:PATH"
            Write-Host $env:PATH
        }
        else {
            Write-Host "OpenDAQ installation failed with exit code $($process.ExitCode)"
            exit $process.ExitCode
        }

    - name: Install openDAQ framework package (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo dpkg -i "${{ inputs.opendaq-framework-package-path }}/${{ inputs.opendaq-framework-package-filename }}"

    - name: Unsupported runner OS
      if: runner.os != 'Windows' && runner.os != 'Linux'
      shell: bash
      run: |
        echo "Install openDAQ is not supported for ${{ runner.os }}"
        exit 1
